name: Generate Terraform Documentation

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
       
      - name: Install terraform-docs
        run: |
          
          wget https://github.com/terraform-docs/terraform-docs/releases/download/v0.15.0/terraform-docs-v0.15.0-linux-amd64.tar.gz
          tar -xzf terraform-docs-v0.15.0-linux-amd64.tar.gz
          sudo mv terraform-docs /usr/local/bin/

      - name: Generate Documentation
        run: terraform-docs markdown table . > DOCUMENTATION.md

      - name: Commit Documentation
        run: |
         
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add DOCUMENTATION.md
          git commit -m "docs: update generated documentation [skip ci]" || echo "No changes to commit"

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
